
import { Toaster } from "react-hot-toast";
import ConvexClientProvider from "./ConvexClientProvider";
import "./globals.css";
import Provider from "./provider";
import AppSideBar from "@/components/custom/AppSideBar";
import { SidebarProvider,SidebarTrigger } from "@/components/ui/sidebar";
import Header from "@/components/custom/Header";
import { Ubuntu } from "next/font/google"

const ubuntu = Ubuntu({
    subsets: ['latin'],
    weight: ['400', '500', '700'],
    variable: '--font-ubuntu',
    display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`overflow-y-scroll ${ubuntu.className} [&::-webkit-scrollbar]:hidden`}>
        <ConvexClientProvider>
          <Provider>
            <SidebarProvider
              defaultOpen={false}
              style={{
                "--sidebar-width" : "18rem",
                "--sidebar-width-mobile": "20rem",
              }}
            >
              <div className="flex w-full">
                <AppSideBar/>
                <div className="flex flex-col w-full">
                  <Header/>
                  <main className="p-4 w-full">
                    {children}
                  </main>
                  <Toaster/>
                </div>
              </div>
            </SidebarProvider>
            <Toaster/>
          </Provider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
