import { Toaster } from "@/components/ui/sonner";
import ConvexClientProvider from "./ConvexClientProvider";
import "./globals.css";
import Provider from "./provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="overflow-y-scroll [&::-webkit-scrollbar]:hidden">
        <ConvexClientProvider>
          <Provider>
            {children}
            <Toaster/>
          </Provider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
